### PR TITLE
Rerender2

### LINKED ISSUE #7: ENH: re-render
We need a re-render to support py36

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #7

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/pyfai ready for review

**Comment by tacaswell** [comment]
Why two commits?

**Comment by CJ-Wright** [comment]
I think one was done before I had downloaded the OSX stuff. I can rebase if you want.

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
