### PR TITLE
bump to v2023.1.0 and update build to meson

### PR DESCRIPTION
**Pull request by t20100**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by t20100** [comment]
@conda-forge-admin, please rerender

**Comment by kif** [comment]
Do you have an idea why 
```2023-01-27T08:33:45.4194762Z Error: Failed to render jinja template in /home/conda/recipe_root/meta.yaml:
2023-01-27T08:33:45.4197141Z 'PYTHON' is undefined
```

**Comment by kif** [comment]
@conda-forge-admin, please rerender

**Comment by t20100** [comment]
> Do you have an idea why 'PYTHON' is undefined

No... Let's change one thing at a time, I switched back to using scripts.

**Comment by t20100** [comment]
`ValueError: ZIP does not support timestamps before 1980` on osx....

**Comment by kif** [comment]
Shit, that's a hidden feature of git which is used under-the-hood to perform the `sdist`.

**Comment by kif** [comment]
What about touching all files recursively after untar ?

**Comment by kif** [comment]
pourtant ca passe sur le mac-mini

**Comment by kif** [comment]
Thanks a lot Thomas.

**Pull request merged**
