### PR TITLE
check against xpdtools

### PR DESCRIPTION
**Pull request by CJ-Wright**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Attn: @msarahan This is using the fancy new conda-build test feature!

**Comment by CJ-Wright** [comment]
@sbillinge this means that now every attempt to build pyFAI is checked against xpdtools to make sure that the API/build is compatible.

**Comment by msarahan** [comment]
Great!  I hope it proves useful.  We have encountered some issues with it that I think are specific to how our build system works, but please let me know (in conda-build github issues) if you hit problems.  Releasing 3.10.1 now with some fixes...

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Pull request closed without merging**
