### PR TITLE
Home

### PR DESCRIPTION
**Pull request by CJ-Wright**
Update some info in the recipe, nothing critical to the package itself so no build bump.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
closes #3

**Comment by tacaswell** [comment]
Please bump the build number.

**Comment by CJ-Wright** [comment]
Pending fabio numpy 1.13 support

**Comment by CJ-Wright** [comment]
@conda-forge/pyfai ready for review.

**Comment by tacaswell** [comment]
Why no np 1.13 + py36?

**Comment by CJ-Wright** [comment]
Idk, that seems to be how the re-render worked.
I have opened an issue at the smithy https://github.com/conda-forge/conda-smithy/issues/538

**Comment by CJ-Wright** [comment]
@tacaswell ready for merge?

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
