### PR TITLE
Disable pypy

### PR DESCRIPTION
**Pull request by kif**
let's try smth

### CODE REVIEW

**Review by CJ-Wright — CHANGES_REQUESTED** [review]
Please do this by removing the pypy migrator file and rerendering

**Comment by kif** [comment]
I am sorry, I don't understand (and I don't use conda neither ...)

**Comment by t20100** [comment]
I guess you should remove the `.ci_support/migrations/pypy.yaml` file.

**Comment by kif** [comment]
Nop: those files are apparently auto-generated.
Sam suggests this:
https://conda-forge.org/docs/maintainer/knowledge_base.html#pypy-builds

**Comment by kif** [comment]
I tried the other way in #44

**Pull request closed without merging**
