### PR TITLE
Remove pypy, version4

### PR DESCRIPTION
**Pull request by kif**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [-] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

disable pypy 4th iteration

### CODE REVIEW

**Comment by kif** [comment]
@conda-forge-admin please rerender

**Comment by kif** [comment]
Is this correct ?

**Review by CJ-Wright — APPROVED** [review]
Looks great! Do we need to mark the pypy pkgs as broken?

**Comment by kif** [comment]
Well, if they packaged (which seams unlikely to me ...) they are maybe somehow usable: most Cython code in pyFAI has pure numpy fall-back to ensure the consistency of the code. While pypy makes python much faster, it does not accelerate the part we are interested in. I would not invest much effort in that direction. just leave it as it is.

**Pull request merged**
