### PR TITLE
Add ppc64le build

### LINKED ISSUE #48: Add build for linux-ppc64le
Adding `linux-ppc64le` as a target platform is pretty straightforward but some direct or indirect dependencies are not built yet for ppc64le. Here is a non exhaustive list:

 - [ ] fabio conda-forge/fabio-feedstock#32
 - [ ] hdf5plugin conda-forge/hdf5plugin-feedstock#17
 - [ ] silx-base conda-forge/silx-feedstock#37

Installing from `pypi` works fine, but with a few glitches, e.g. the entry points are not properly installed.

Once the dependencies are satisfied, I'll open a MR to add the `linux-ppc64le` platform.

### PR DESCRIPTION
**Pull request by sdebionne**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #48

### CODE REVIEW

**Comment by sdebionne** [comment]
@conda-forge-admin, please rerender

**Comment by sdebionne** [comment]
Complaining about `silx-base` not being available but it's definitely avail... some cache effect?

@conda-forge-admin, please restart ci

**Comment by CJ-Wright** [comment]
You might consider adding this to the ppc migration here: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt adding pyfai to that file will make certain that all deps are built and issue the migration PRs in order

**Comment by sdebionne** [comment]
@CJ-Wright Thanks for the heads-up, I had no idea there was such migration procedure. Quick question: while the deps are available on anaconda (`silx-base` in this case), conda-forge running Azure CI cannot find them, any idea why?

**Comment by CJ-Wright** [comment]
You most likely have a qt dep somewhere, I would add pyfai to the migration and it will sort out if pyfai can be migrated yet.

**Comment by t20100** [comment]
Closing, `ppc64le` was added in PR #64

**Pull request closed without merging**
