### PR TITLE
Split into two packages

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@kif @t20100 let me know what you think...
Thanks!

**Comment by kif** [comment]
Hi Tom,
You would like to split pyFAI into two with different dependencies ... like the debian package pyFAI and python3-pyFAI: the former is the application and the later the library ?

Concerning dependencies, numexpr is used in the goniometer, scipy is probably used at various places, h5py is used to store and restore the detector definition and finally silx is used for any OpenCL application.

So the dependency on silx is hard to remove. If numexpr or h5py are missing, some feature may be deactivated or unusable.

**Comment by t20100** [comment]
This looks good to me provided that this PR https://github.com/conda-forge/fabio-feedstock/pull/25/ gets into fabio to put the dependencies where they belong.
It's basically splitting the lib from the GUI as much as it can.

I fixed a small typo in the `meta.yml` file.

**Comment by tschoonj** [comment]
Hi Jerome,

I would indeed like to split pyFAI in a similar way as what happens in Debian. I did something similar [yesterday](https://github.com/conda-forge/silx-feedstock/pull/29) for silx as well.

This PR introduces a `pyFAI-base` subpackage, which drags in the dependencies listed in pyFAI's `setup.py` [`install_requires`](https://github.com/silx-kit/pyFAI/blob/79a61442126f5a44db62b23f40efc455e8d3ad5a/setup.py#L964-L977), and includes `silx-base` (basically again those deps listed in its `install_requires`, so non-GUI deps only).

However, the `pyFAI` subpackage continues to drag in (most) dependencies that come with a full gui installation.

The goal of my work here is to ensure that we can have a deployment of pyFAI that drags in only non-gui dependencies, and particularly excludes PyQT. I hope this PR will accomplish this: please let me know if I got something wrong.

**Comment by tschoonj** [comment]
@t20100 Please revert your commit: this was not a typo :smile:

**Comment by tschoonj** [comment]
I will have a look at your fabio conda-forge PR... sorry I had forgotten about it!

**Comment by t20100** [comment]
Oups my bad, I miss read it... still learning `meta.yml` syntax as I go...

**Comment by tschoonj** [comment]
> Oups my bad, I miss read it... still learn `meta.yml` syntax as I go...

Yeah subpackages are pretty confusing. I even ended up doing this PR quite differently compared to the silx one from yesterday...

**Comment by tschoonj** [comment]
Are there any objections to this PR, or can I merge it in?

Thanks,

Tom

**Comment by t20100** [comment]
Done!

**Comment by tschoonj** [comment]
Many thanks!

**Pull request merged**
