### PR TITLE
Fix conda-list warning

### PR DESCRIPTION
**Pull request by tschoonj**
See https://github.com/conda-forge/fabio-feedstock/issues/21

Also: add myself as maintainer

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tschoonj** [comment]
@conda-forge-admin, please rerender

**Comment by tschoonj** [comment]
@conda-forge-admin, please rerender

**Comment by tschoonj** [comment]
@conda-forge-admin, please rerender

**Comment by tschoonj** [comment]
@CJ-Wright Any thoughts about this?

**Comment by CJ-Wright** [comment]
This seems reasonable, does linux not need the build flag?

**Comment by tschoonj** [comment]
It would appear that `install` implies `build`, if not called before.

**Comment by CJ-Wright** [comment]
Ah ok, in that case LGTM

**Comment by tschoonj** [comment]
Thanks!

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
